"""Add BaseModel

Revision ID: f01254b2be7d
Revises: 45e358450714
Create Date: 2022-11-15 16:20:53.869824

"""
from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01254b2be7d'
down_revision = '45e358450714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('charityproject', schema=None) as batch_op:
        batch_op.alter_column('full_amount',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
